### ISSUE TITLE
GPU is not used even if you have set GPU.

### ISSUE THREAD

**Issue by maxbizz** [rudymohammadbali/OpenAI-Whisper-GUI#13] opened 2024-07-01 11:30 UTC
First of all i get this warning " UserWarning: FP16 is not supported on CPU; using FP32 instead
  warnings.warn("FP16 is not supported on CPU; using FP32 instead")" 
  
  And when i set the device to GPU and transcribe , My CPU usage spikes up to 100% and the process becomes painfully slow. GPU is not used at all.

**Comment by rudymohammadbali** [comment] 2024-07-01 20:30
Oh, the issue is at line 368 in functions.py file, where it's checks if device options is in: cuda or cpu
But device options was passed as gpu and not cuda therefore its using cpu!

**Comment by rudymohammadbali** [comment] 2024-07-02 23:56
@maxbizz 

The issue should have been fixed now. Check functions.py file for changes!

**Closed** 2024-07-05 00:26 UTC
